spring:
  profiles:
    active: dev
  mvc:
    # 404 交给异常处理器处理
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false


# mybatis
mybatis:
  mapper-locations: "classpath:mybatis/*Mapper.xml"