spring:
  profiles:
    active: dev
  mvc:
    # 404 交给异常处理器处理
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false

  datasource:
    url: @datasource.url@
    username: @datasource.username@
    password: @datasource.password@
    driver-class-name: com.mysql.cj.jdbc.Driver

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB

logging:
  level:
    win.ots.hello.dao : debug

# mybatis
#mybatis:
#  mapper-locations: "classpath:mapper/*Mapper.xml"

common:
  base-upload-file: /home/otswang/workplace/upload/
