# 开发环境配置
spring:
  datasource:
    url: jdbc:mysql://manjaro:3306/test
    username: test
    password: test123456
    driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  level:
    win.ots.hello.dao : debug
